### ISSUE TITLE
Feature Request: Force version manually

### ISSUE THREAD

**Issue by GaryCraft** [mxve/plutonium-updater.rs#1]
I know this might be a weird one, but it might be useful to have a version to force, as an argument, would it be possible to get it from the CDN by version?

This might enable to not update to an incompatible version or to go back to some versions temporarily if newer ones cause problems

**Comment by mxve** [comment]
Afaik the CDN only serves the latest version of each file. And even if older versions of the files were still available, there wouldn't be a way to get the name of the file.
The file names on the CDN are SHA1 hashes of the files that are obtained from https://cdn.plutonium.pw/updater/prod/info.json, without this hash we aren't able to download the file. There is no (public) archive of versions.
![](https://screen.sbs/i/464waumd.png)


I'm going to implement a small backup system to allow going back to a previously insatlled version

ToDo (subject to change):
- [ ] automatically backup changed files to $installdir/backup/$version/
  - [ ] ? pack & compress as archive rather than keeping the loose files
  - [ ] keep a max of _n_ versions (probably 3)
- [ ] list backups with --backup_list
- [ ] restore backed up version with --backup_restore <version>
- [ ] disable backups with --no_backup

**Comment by mxve** [comment]
I've implemented the backup feature.
I still have to do a bit more testing before publishing a release. This issue will be closed once a release has been published.

**Comment by mxve** [comment]
https://github.com/mxve/plutonium-updater.rs/releases/tag/v0.3.0
